apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tkw8k2o4e-go
  janus-idp.io/tekton: tkw8k2o4e-go
  backstage.io/kubernetes-id: tkw8k2o4e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tkw8k2o4e-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
