apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tkw8k2o4e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tkw8k2o4e-go 
  name: tkw8k2o4e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tkw8k2o4e-go 
